name: Ruby Gem

on: [push]

jobs:
  minitest:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Set up Ruby 2.7.1
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.x

      - name: Run minitest
        run: |
          bundle install
          bundle exec rake test

  publish:
    name: Publish
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/master'

    needs: minitest

    steps:
      - uses: actions/checkout@master

      - name: Set up Ruby 2.7
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.x

      - name: Publish to RubyGems
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          gem build *.gemspec
          gem push *.gem
        env:
          GEM_HOST_API_KEY: ${{secrets.RUBYGEMS_AUTH_TOKEN}}
